<a href="https://colab.research.google.com/github/YunSeoHwan/My-own-study-repository/blob/main/DeepLearning/3_4_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **기본 연산 실습**

In [1]:
import torch

In [3]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])

b = torch.FloatTensor([[2, 2],
                       [3, 3]])

print(a + b)

tensor([[3., 4.],
        [6., 7.]])


In [5]:
# 사칙연산
print(a - b)
print(a * b)
print(a / b)

# 제곱
print(a ** b)

tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[ 1.,  4.],
        [27., 64.]])


In [6]:
# 논리연산
print(a == b)
print(a != b)

tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])


# **인플레이스 연산**

In [7]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [8]:
# 새로운 메모리에 할당됨.
print(a.mul(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [9]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [10]:
# 메모리 관리 알아서 되므로, 굳이 사용 x
print(a.mul_(b))
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


# **차원 축소 연산**

In [13]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

# 합, 평균은 스칼라로 저장
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [15]:
# dim 연산
print(x.sum(dim = 0))     # 첫번째 차원에 관해 연산 -> 세로 연산
print(x.sum(dim = -1))    # 가로 연산

tensor([4., 6.])
tensor([3., 7.])


# **브로드캐스트 연산**

In [16]:
# tensor + scala
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [17]:
# tensor + vetor
x = torch.FloatTensor([[1, 2],
                       [4, 8]])

y = torch.FloatTensor([3, 5])

z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [19]:
# tensor + tensor
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

z = x + y
print(z)
print(z.size())

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])
