<a href="https://colab.research.google.com/github/YunSeoHwan/My-own-study-repository/blob/main/DeepLearning/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **파이토치 텐서 생성하기**

In [1]:
import torch

In [2]:
# 실수형 Tensor 생성
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])

print(ft)

tensor([[1., 2.],
        [3., 4.]])

In [9]:
# Long, Byte Tensor
lt = torch.LongTensor([[1, 2],
                        [3, 4]])

bt = torch.ByteTensor([[1, 0],
                       [0, 1]])

print(lt, bt)

(tensor([[1, 2],
         [3, 4]]), tensor([[1, 0],
         [0, 1]], dtype=torch.uint8))

In [10]:
# 임의의 값 Tensor
x = torch.FloatTensor(3, 2)

print(x)

tensor([[3.2799e-34, 0.0000e+00],
        [8.5479e-44, 4.4842e-44],
        [1.6255e-43, 1.5554e-43]])

# **Numpy 호환**

In [11]:
import numpy as np

In [12]:
x = np.array([[1, 2],
              [3, 4]])      # array 정의

print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [13]:
# ndarray -> tensor 전환
x = torch.from_numpy(x)

print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [14]:
# tensor -> ndarray 전환
x = x.numpy()

print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [17]:
# type 변환
ft.long()

lt.float()

tensor([[1., 2.],
        [3., 4.]])

# **Tensor 크기 구하기**

In [19]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [22]:
# 차원 indexing
print(x.size(1))
print(x.shape[1])

3
2


In [23]:
# tensor 차원 개수
print(x.dim())
print(len(x.size()))

3
3
